{
	"version": 1485089430,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background.png",
		"images/solidtile.png",
		"images/jumpthrutile.png",
		"images/pl-sheet0.png",
		"images/pl-sheet1.png",
		"images/background2.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/pav1-sheet0.png",
		"images/ombra-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/ondarossa-sheet0.png",
		"images/ondaverde-sheet0.png",
		"images/ondaviola-sheet0.png",
		"images/glowweapon-sheet0.png",
		"images/glowweapon-sheet1.png",
		"images/gennaro-sheet0.png",
		"images/frankie-sheet0.png",
		"images/carmelo-sheet0.png",
		"images/indicator-sheet0.png",
		"images/pavimentorottto1-sheet0.png",
		"images/parco1.png",
		"images/prato1-sheet0.png",
		"images/prato2-sheet0.png",
		"images/parco2.png",
		"images/parco3.png",
		"images/cestino-sheet0.png",
		"images/insulti6-sheet0.png",
		"images/insulti6-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/tiledbackground2.png",
		"images/lore1-sheet0.png",
		"images/lore2-sheet0.png",
		"images/lore3-sheet0.png",
		"media/saw bar wav.m4a",
		"media/saw bar wav.ogg",
		"media/sine 16.m4a",
		"media/sine 16.ogg",
		"media/square 16.m4a",
		"media/square 16.ogg",
		"media/sine definitivo porco dio.m4a",
		"media/sine definitivo porco dio.ogg",
		"media/start (grifo).ogg",
		"media/3 livello - fidanzata.m4a",
		"media/3 livello - fidanzata.ogg",
		"media/corridoio.m4a",
		"media/corridoio.ogg",
		"media/start (grifo).m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"intro - sfumatura menu.mp4"
	]
}